---
test:
  workers:
    type: local
    number: 5
  rounds:
    - label: Change car owner.
      txDuration: 30
      rateControl:
        type: fixed-backlog
        opts:
          unfinished_per_client: 5
      arguments:
        assets: 1000
      callback: benchmarks/fabcar/changeCarOwner.js
    - label: Query all cars.
      txDuration: 30
      rateControl:
        type: fixed-backlog
        opts:
          unfinished_per_client: 5
      arguments:
        assets: 1000
        startKey: "1"
        endKey: "50"
      callback: benchmarks/fabcar/queryAllCars.js
    - label: Query a car.
      txDuration: 30
      rateControl:
        type: fixed-backlog
        opts:
          unfinished_per_client: 5
      arguments:
        assets: 1000
      callback: benchmarks/fabcar/queryCar.js
    - label: Create a car.
      txDuration: 30
      rateControl:
        type: fixed-backlog
        opts:
          unfinished_per_client: 5
      callback: benchmarks/fabcar/createCar.js
monitor:
  type:
    - docker
  docker:
    name:
      - all
  interval: 1
