global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "nodeexporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "hyperledger_metrics"
    scrape_interval: 10s
    static_configs:
      - targets:
          [
            "orderer.example.com:7053",
            "orderer2.example.com:8053",
            "orderer3.example.com:9053",
            "orderer4.example.com:10053",
            "orderer5.example.com:11053",
            "peer0.org1.example.com:12053",
            "peer1.org1.example.com:13053",
            "peer0.org2.example.com:14053",
            "peer1.org2.example.com:15053",
          ]

  - job_name: "pushgateway"
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"
