---
test:
  workers:
    type: local
    number: 5
  rounds:
    - label: addAsset.
      txDuration: 30
      rateControl:
        type: fixed-backlog
        opts:
          unfinished_per_client: 5
      arguments:
        assets: 1000
      callback: benchmarks/registerAsset/addAsset.js
    - label: getAsset.
      txDuration: 30
      rateControl:
        type: fixed-backlog
        opts:
          unfinished_per_client: 5
      arguments:
        assets: 1000
        startKey: "1"
        endKey: "50"
      callback: benchmarks/registerAsset/getAsset.js
monitor:
  type:
    - docker
  docker:
    name:
      - all
  interval: 1
